package com.rovio.daily3

import android.app.*;import android.os.*;import android.content.*;import android.widget.Toast;import androidx.activity.ComponentActivity;import androidx.activity.compose.setContent;import androidx.compose.animation.core.*;import androidx.compose.foundation.*;import androidx.compose.foundation.gestures.detectTapGestures;import androidx.compose.foundation.layout.*;import androidx.compose.foundation.lazy.grid.*;import androidx.compose.foundation.shape.*;import androidx.compose.material3.*;import androidx.compose.runtime.*;import androidx.compose.ui.*;import androidx.compose.ui.draw.*;import androidx.compose.ui.geometry.Offset;import androidx.compose.ui.graphics.*;import androidx.compose.ui.input.pointer.pointerInput;import androidx.compose.ui.text.font.*;import androidx.compose.ui.text.style.*;import androidx.compose.ui.unit.*;import androidx.lifecycle.*;import androidx.lifecycle.viewmodel.compose.viewModel;import androidx.room.*;import androidx.sqlite.db.SupportSQLiteDatabase;import kotlinx.coroutines.*;import kotlinx.coroutines.flow.*;import androidx.datastore.preferences.core.*;import androidx.datastore.preferences.preferencesDataStore;import androidx.work.*;import java.time.*;import java.time.format.*;import java.util.concurrent.TimeUnit

val Context.store by preferencesDataStore("rovio")
@Entity data class ShortSlot(@PrimaryKey val id:Int,val title:String="",val status:String="TODO",val startTime:Long?=null,val doneTime:Long?=null,val label:String)
@Entity data class ArchiveDay(@PrimaryKey val date:String,val count:Int,val titles:String,val realDurations:String)
@Entity data class RushAttempt(@PrimaryKey(autoGenerate=true) val id:Int=0,val slot:Int,val time:Long,val earlyBy:Long)
@Entity data class StackedAttempt(@PrimaryKey(autoGenerate=true) val id:Int=0,val fromSlot:Int,val toSlot:Int,val time:Long,val waitLeft:Long)
@Dao interface Dao{ @Query("select * from ShortSlot order by id") fun slots():Flow<List<ShortSlot>>; @Query("select * from RushAttempt order by time desc") fun rush():Flow<List<RushAttempt>>; @Query("select * from StackedAttempt order by time desc") fun stacked():Flow<List<StackedAttempt>>; @Query("select * from ArchiveDay order by date desc limit 30") fun archive():Flow<List<ArchiveDay>>; @Insert(onConflict=OnConflictStrategy.REPLACE) suspend fun upsert(s:ShortSlot); @Insert suspend fun rush(a:RushAttempt); @Insert suspend fun stack(a:StackedAttempt); @Insert(onConflict=OnConflictStrategy.REPLACE) suspend fun archive(a:ArchiveDay); @Query("delete from ShortSlot") suspend fun clear() }
@Database(entities=[ShortSlot::class,ArchiveDay::class,RushAttempt::class,StackedAttempt::class],version=1) abstract class Db:RoomDatabase(){abstract fun dao():Dao; companion object{fun make(c:Context)=Room.databaseBuilder(c,Db::class.java,"rovio.db").addCallback(object:Callback(){override fun onCreate(db:SupportSQLiteDatabase){db.execSQL("insert into ShortSlot(id,title,status,label) values(1,'','TODO','MORNING'),(2,'','TODO','AFTERNOON'),(3,'','TODO','EVENING')")}}).build()}}
class TickWorker(c:Context,p:WorkerParameters):CoroutineWorker(c,p){override suspend fun doWork()=Result.success()}
class Vm(app:Application):AndroidViewModel(app){private val d=Db.make(app).dao(); val slots=d.slots().stateIn(viewModelScope,SharingStarted.Eagerly,emptyList()); val rush=d.rush().stateIn(viewModelScope,SharingStarted.Eagerly,emptyList()); val stacked=d.stacked().stateIn(viewModelScope,SharingStarted.Eagerly,emptyList()); val archive=d.archive().stateIn(viewModelScope,SharingStarted.Eagerly,emptyList()); val tab=MutableStateFlow(0); private val last=longPreferencesKey("lastArmTime"); init{WorkManager.getInstance(app).enqueueUniquePeriodicWork("timer",ExistingPeriodicWorkPolicy.KEEP,PeriodicWorkRequestBuilder<TickWorker>(15,TimeUnit.MINUTES).build())} fun tap(s:ShortSlot){viewModelScope.launch{val now=System.currentTimeMillis(); if(s.status=="TODO"){val l=getApplication<Application>().store.data.first()[last]?:0; if(now-l<900000){d.stack(StackedAttempt((0),slots.value.firstOrNull{it.status=="DOING"}?.id?:0,s.id,now,900000-(now-l))); vib(); return@launch}; getApplication<Application>().store.edit{it[last]=now}; d.upsert(s.copy(status="DOING",startTime=now))}}} fun confirm(s:ShortSlot){viewModelScope.launch{val now=System.currentTimeMillis(); val st=s.startTime?:now; if(now-st>=3600000){d.upsert(s.copy(status="DONE",doneTime=now)); vib()}else{d.rush(RushAttempt(slot=s.id,time=now,earlyBy=3600000-(now-st))); vib(); Toast.makeText(getApplication(),"Too early - ${fmt(3600000-(now-st))} left",Toast.LENGTH_SHORT).show()}}} fun title(s:ShortSlot,t:String){viewModelScope.launch{d.upsert(s.copy(title=t.take(42),status=if(t.isBlank()&&s.status=="DOING")"TODO" else s.status,startTime=if(t.isBlank())null else s.startTime))}} private fun vib(){val v=getApplication<Application>().getSystemService(Context.VIBRATOR_SERVICE) as Vibrator; if(Build.VERSION.SDK_INT>=26)v.vibrate(VibrationEffect.createWaveform(longArrayOf(30,20,30),-1)) else @Suppress("DEPRECATION") v.vibrate(80)}}
class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);setContent{App()}}}
val Desk=Color(0xFF121417);val Paper=Color(0xFFF5F3EF);val Ink=Color(0xFF0B0F19);val Red=Color(0xFFE54D2E);val Sage=Color(0xFF8FA68E);val Clay=Color(0xFFC9A67A);val Muted=Color(0xFF8C8A86)
@Composable fun App(vm:Vm= viewModel()){val tab by vm.tab.collectAsState();MaterialTheme{Column(Modifier.fillMaxSize().background(Desk).padding(16.dp)){TabRow(selectedTabIndex=tab,containerColor=Desk,contentColor=Paper){listOf("TODAY","TIME VAULT","AUDIT").forEachIndexed{i,t->Tab(tab==i,{vm.tab.value=i},text={Text(t)})}}; when(tab){0->Today(vm);1->Vault(vm);else->Audit(vm)}}}}
@OptIn(ExperimentalLayoutApi::class)
@Composable fun Header(){var now by remember{mutableStateOf(System.currentTimeMillis())};LaunchedEffect(0){while(true){now=System.currentTimeMillis();delay(1000)}}; val left=nextIst(now);Row(Modifier.fillMaxWidth().height(72.dp),horizontalArrangement=Arrangement.SpaceBetween){Column{Text("14",fontSize=44.sp,fontFamily=FontFamily.Serif,color=Paper);Row{repeat(14){Box(Modifier.size(1.5.dp,10.dp).background(Paper));Spacer(Modifier.width(3.dp))}};Text("DAY RUN",fontSize=8.sp,color=Muted)};Column(horizontalAlignment=Alignment.CenterHorizontally){FlowRow(maxItemsInEachRow=11,horizontalArrangement=Arrangement.spacedBy(4.dp)){repeat(21){Box(Modifier.size(6.dp).clip(CircleShape).border(1.2.dp,Paper,CircleShape).background(if(it<14)Paper else Color.Transparent))}};Text("14/21  WEEK",fontSize=10.sp,fontFamily=FontFamily.Monospace,color=Paper)};Column(horizontalAlignment=Alignment.End){Box(Modifier.size(28.dp,32.dp).rotate(3f).background(Sage).border(1.5.dp,Ink)){Text("1",Modifier.align(Alignment.Center),fontSize=11.sp,fontFamily=FontFamily.Monospace,color=Ink)};Text("SHIELD",fontSize=7.sp,color=Muted);Text(fmt(left),fontSize=10.sp,fontFamily=FontFamily.Monospace,color=if(left<600000)Red else Paper);Text("TILL 1AM IST",fontSize=7.sp,color=Muted)}}}
fun nextIst(now:Long):Long{val z=ZoneOffset.ofHoursMinutes(5,30); val n=Instant.ofEpochMilli(now).atZone(z); val target=if(n.hour<1)n.toLocalDate().atTime(1,0) else n.toLocalDate().plusDays(1).atTime(1,0);return Duration.between(n,target.atZone(z)).toMillis()}
@Composable fun Today(vm:Vm){val slots by vm.slots.collectAsState();val arc by vm.archive.collectAsState(); var edit by remember{mutableStateOf<ShortSlot?>(null)};Header();Text("TODAY'S EDITION — 3 STORIES",fontSize=9.sp,color=Muted,letterSpacing=0.08.em);slots.forEach{SlotCard(it,{vm.tap(it)},{vm.confirm(it)},{edit=it})};Text("ARCHIVE — 30D",fontSize=8.sp,color=Muted,modifier=Modifier.padding(top=14.dp));LazyVerticalGrid(columns=GridCells.Fixed(6),modifier=Modifier.height(220.dp),horizontalArrangement=Arrangement.spacedBy(10.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){items(30){i->val a=arc.getOrNull(i);Box(Modifier.aspectRatio(1f).shadowBox(RoundedCornerShape(6.dp))){Text("${i+1}",fontSize=9.sp,fontFamily=FontFamily.Monospace,color=Ink);Row(Modifier.align(Alignment.Center)){repeat(a?.count?:0){Box(Modifier.size(6.dp).clip(CircleShape).background(if(a.count==3)Red else Clay))}}}}};edit?.let{s->var t by remember(s){mutableStateOf(s.title)};AlertDialog(onDismissRequest={edit=null},confirmButton={Button({vm.title(s,t);edit=null}){Text("SAVE")}},title={Text("Edit title")},text={TextField(t,{t=it},maxLines=1)})}}
fun Modifier.shadowBox(shape:Shape)=this.padding(end=5.dp,bottom=5.dp).drawBehind{drawRoundRect(Ink,topLeft=Offset(5.dp.toPx(),5.dp.toPx()))}.clip(shape).background(Paper).border(2.dp,Ink,shape)
@Composable fun SlotCard(s:ShortSlot,onTap:()->Unit,onConfirm:()->Unit,onEdit:()->Unit){val shape=RoundedCornerShape(if(s.id==1)14.dp else if(s.id==2)4.dp else 12.dp,if(s.id==1)4.dp else 14.dp,if(s.id==1)12.dp else if(s.id==2)4.dp else 14.dp,if(s.id==1)4.dp else 12.dp);Row(Modifier.fillMaxWidth().height(108.dp).padding(vertical=6.dp).graphicsLayer(rotationZ=listOf(-1.2f,.8f,-.6f)[s.id-1]).shadowBox(shape).padding(12.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.width(60.dp)){Text("0${s.id}",fontSize=32.sp,fontFamily=FontFamily.Serif,color=Ink.copy(alpha=if(s.status=="TODO") .2f else 1f));Text(s.label,fontSize=7.sp,color=Muted)};Text(if(s.title.isBlank())"Add title..." else s.title,Modifier.weight(1f).clickable{onEdit()},fontSize=14.sp,fontWeight=FontWeight.Medium,color=if(s.title.isBlank())Muted else Ink,maxLines=1,overflow=TextOverflow.Ellipsis);Column(horizontalAlignment=Alignment.CenterHorizontally){Box(Modifier.size(38.dp).clip(CircleShape).background(if(s.status=="DOING")Sage else if(s.status=="DONE")Red else Color.Transparent).border(2.dp,if(s.status=="DONE")Red else Ink,CircleShape).pointerInput(s){detectTapGestures(onTap={onTap()},onLongPress={onConfirm()})}){Text(if(s.status=="DONE")"✓" else if(s.status=="DOING")"•" else "",Modifier.align(Alignment.Center),color=Color.White,fontSize=18.sp)};Text(s.status,fontSize=7.sp,fontFamily=FontFamily.Monospace,color=Muted); if(s.doneTime!=null)Text("done "+time(s.doneTime),fontSize=8.sp,color=Muted)}}}
@Composable fun Vault(vm:Vm){val slots by vm.slots.collectAsState();val rush by vm.rush.collectAsState();val stacked by vm.stacked.collectAsState();var now by remember{mutableStateOf(System.currentTimeMillis())};LaunchedEffect(0){while(true){now=System.currentTimeMillis();delay(1000)}};Column(Modifier.verticalScroll(rememberScrollState())){slots.forEach{s->val rem=(s.startTime?.let{3600000-(now-it)}?:0).coerceAtLeast(0);Text("0${s.id} ${if(s.status=="DOING"&&rem>0)fmt(rem)+" left" else if(s.status=="DOING")"Ready to confirm" else s.status}",color=Paper,fontFamily=FontFamily.Monospace);LinearProgressIndicator(progress={if(s.startTime==null)0f else ((now-s.startTime)/3600000f).coerceIn(0f,1f)},color=Sage)};Text("Rush attempts",color=Red);rush.forEach{Text("0${it.slot} early by ${fmt(it.earlyBy)}",color=Paper)};stacked.forEach{Text("0${it.toSlot} locked - ${fmt(it.waitLeft)} cooldown",color=Paper)};val deep=slots.sumOf{if(it.status=="DONE"&&it.doneTime!=null&&it.startTime!=null)it.doneTime-it.startTime else if(it.status=="DOING"&&it.startTime!=null)now-it.startTime else 0};Text("Deep Work Today ${"%.1f".format(deep/3600000.0)}h / 3h deep work",color=Paper)}}
@Composable fun Audit(vm:Vm){Column{listOf("MON","TUE","WED","THU","FRI","SAT","SUN").forEachIndexed{i,d->Text("$d: 01 ${60+i}m legit / 02 ${42+i}m rushed amber / 03 1h30m legit - Grade ${if(i<3)'B' else 'A'}",color=Paper,fontSize=12.sp)}}}
fun fmt(ms:Long):String{val s=ms/1000;return "%02d:%02d:%02d".format(s/3600,(s%3600)/60,s%60)};fun time(ms:Long)=DateTimeFormatter.ofPattern("h:mma").format(Instant.ofEpochMilli(ms).atZone(ZoneId.systemDefault())).lowercase()
